// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'saranya_firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class SaranyaFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXvr83cHKuoEFkYK0uLUwQHS5XmnYhfb4',
    appId: '1:414290269238:web:1e0817b68074bcffd5f497',
    messagingSenderId: '414290269238',
    projectId: 'saranya-a8742',
    authDomain: 'saranya-a8742.firebaseapp.com',
    storageBucket: 'saranya-a8742.firebasestorage.app',
    measurementId: 'G-VETQPWJNKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPxxPnqGIz-DNoTPnUXTMQXd6Wf2YCDCk',
    appId: '1:414290269238:android:584cf889f0f6a239d5f497',
    messagingSenderId: '414290269238',
    projectId: 'saranya-a8742',
    storageBucket: 'saranya-a8742.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAErMf7GJXlb8hj13ywcAFKZDHbmGqi4Ko',
    appId: '1:414290269238:ios:c8e2a4a2927d7278d5f497',
    messagingSenderId: '414290269238',
    projectId: 'saranya-a8742',
    storageBucket: 'saranya-a8742.firebasestorage.app',
    iosBundleId: 'in.easycloud.saranya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAErMf7GJXlb8hj13ywcAFKZDHbmGqi4Ko',
    appId: '1:414290269238:ios:c8e2a4a2927d7278d5f497',
    messagingSenderId: '414290269238',
    projectId: 'saranya-a8742',
    storageBucket: 'saranya-a8742.firebasestorage.app',
    iosBundleId: 'in.easycloud.saranya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXvr83cHKuoEFkYK0uLUwQHS5XmnYhfb4',
    appId: '1:414290269238:web:c35afac203e01b64d5f497',
    messagingSenderId: '414290269238',
    projectId: 'saranya-a8742',
    authDomain: 'saranya-a8742.firebaseapp.com',
    storageBucket: 'saranya-a8742.firebasestorage.app',
    measurementId: 'G-K583XVNE0E',
  );
}
