// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'saranya_firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class SaranyaFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUOqZDYkXkYZReogku7NIolQyC5vFoGq4',
    appId: '1:1038094649031:web:5243e284263c9df46ba0e2',
    messagingSenderId: '1038094649031',
    projectId: 'saranya-3b638',
    authDomain: 'saranya-3b638.firebaseapp.com',
    storageBucket: 'saranya-3b638.firebasestorage.app',
    measurementId: 'G-D6NV717GRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkB4XaNBZxhNl9TUmGIEn6exf5hn1iJjI',
    appId: '1:1038094649031:android:c210b3ac088bc6206ba0e2',
    messagingSenderId: '1038094649031',
    projectId: 'saranya-3b638',
    storageBucket: 'saranya-3b638.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtZDKOhmxnmTJfOTbsXpw5-NOzEvHdIA0',
    appId: '1:1038094649031:ios:116fbc8130ce94456ba0e2',
    messagingSenderId: '1038094649031',
    projectId: 'saranya-3b638',
    storageBucket: 'saranya-3b638.firebasestorage.app',
    iosBundleId: 'in.easycloud.vaidyagrama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtZDKOhmxnmTJfOTbsXpw5-NOzEvHdIA0',
    appId: '1:1038094649031:ios:116fbc8130ce94456ba0e2',
    messagingSenderId: '1038094649031',
    projectId: 'saranya-3b638',
    storageBucket: 'saranya-3b638.firebasestorage.app',
    iosBundleId: 'in.easycloud.vaidyagrama',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUOqZDYkXkYZReogku7NIolQyC5vFoGq4',
    appId: '1:1038094649031:web:05f75637ea54a7906ba0e2',
    messagingSenderId: '1038094649031',
    projectId: 'saranya-3b638',
    authDomain: 'saranya-3b638.firebaseapp.com',
    storageBucket: 'saranya-3b638.firebasestorage.app',
    measurementId: 'G-4SH6TDP74Q',
  );
}
