// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'vaidyagrama_firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class VaidyagramaFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYkGDh9PriZMk8wMrIPXJW8ne0UwjXavY',
    appId: '1:534199255183:web:44984022b51eff2a93f0fa',
    messagingSenderId: '534199255183',
    projectId: 'vaidyagrama-b3b47',
    authDomain: 'vaidyagrama-b3b47.firebaseapp.com',
    storageBucket: 'vaidyagrama-b3b47.firebasestorage.app',
    measurementId: 'G-4XC1BR6B5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPhGSxvzCO_DIOmq3Mr3_ciGgs9_3Oxvg',
    appId: '1:534199255183:android:703b64dc104d71af93f0fa',
    messagingSenderId: '534199255183',
    projectId: 'vaidyagrama-b3b47',
    storageBucket: 'vaidyagrama-b3b47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiQFZ3v_Fnz550LiFjfxc5pDjKGf281e4',
    appId: '1:534199255183:ios:0bae166d9901026193f0fa',
    messagingSenderId: '534199255183',
    projectId: 'vaidyagrama-b3b47',
    storageBucket: 'vaidyagrama-b3b47.firebasestorage.app',
    iosBundleId: 'in.easycloud.vaidyagrama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiQFZ3v_Fnz550LiFjfxc5pDjKGf281e4',
    appId: '1:534199255183:ios:0bae166d9901026193f0fa',
    messagingSenderId: '534199255183',
    projectId: 'vaidyagrama-b3b47',
    storageBucket: 'vaidyagrama-b3b47.firebasestorage.app',
    iosBundleId: 'in.easycloud.vaidyagrama',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYkGDh9PriZMk8wMrIPXJW8ne0UwjXavY',
    appId: '1:534199255183:web:f417dcd1fad03d3e93f0fa',
    messagingSenderId: '534199255183',
    projectId: 'vaidyagrama-b3b47',
    authDomain: 'vaidyagrama-b3b47.firebaseapp.com',
    storageBucket: 'vaidyagrama-b3b47.firebasestorage.app',
    measurementId: 'G-BTE0B8XS2M',
  );
}
