// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'vaidyagrama_firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8DyHl7iUf-bH7J5rkQTphi9iGBTNZaIA',
    appId: '1:683581349799:web:78ebf780c27e72bc232082',
    messagingSenderId: '683581349799',
    projectId: 'vaidyagrama-a9641',
    authDomain: 'vaidyagrama-a9641.firebaseapp.com',
    storageBucket: 'vaidyagrama-a9641.firebasestorage.app',
    measurementId: 'G-13CHL2ERX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANZPXdFRqKsa8Q8hedqQNKleI4zumbCDU',
    appId: '1:683581349799:android:603d1e3464b777d5232082',
    messagingSenderId: '683581349799',
    projectId: 'vaidyagrama-a9641',
    storageBucket: 'vaidyagrama-a9641.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvzyBhwSH0XAz12Q3dcD2W43Qsl1-ZufI',
    appId: '1:683581349799:ios:f347ed016f30b95b232082',
    messagingSenderId: '683581349799',
    projectId: 'vaidyagrama-a9641',
    storageBucket: 'vaidyagrama-a9641.firebasestorage.app',
    iosBundleId: 'in.easycloud.vaidyagrama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvzyBhwSH0XAz12Q3dcD2W43Qsl1-ZufI',
    appId: '1:683581349799:ios:f347ed016f30b95b232082',
    messagingSenderId: '683581349799',
    projectId: 'vaidyagrama-a9641',
    storageBucket: 'vaidyagrama-a9641.firebasestorage.app',
    iosBundleId: 'in.easycloud.vaidyagrama',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8DyHl7iUf-bH7J5rkQTphi9iGBTNZaIA',
    appId: '1:683581349799:web:df2acc86739e5697232082',
    messagingSenderId: '683581349799',
    projectId: 'vaidyagrama-a9641',
    authDomain: 'vaidyagrama-a9641.firebaseapp.com',
    storageBucket: 'vaidyagrama-a9641.firebasestorage.app',
    measurementId: 'G-PGCE2DGBC6',
  );
}
