// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw-EL4ZDhV8ywPNanZWuK5OYM-3DZ-64M',
    appId: '1:355883310220:web:77dfff6d525e1dff606fa9',
    messagingSenderId: '355883310220',
    projectId: 'vaidyagrama-eecc0',
    authDomain: 'vaidyagrama-eecc0.firebaseapp.com',
    storageBucket: 'vaidyagrama-eecc0.firebasestorage.app',
    measurementId: 'G-9T3YX0RPG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1xGiE_mx2aSYNEv7mRssPs9c4QNS4_5k',
    appId: '1:355883310220:android:36806d2b3506f92e606fa9',
    messagingSenderId: '355883310220',
    projectId: 'vaidyagrama-eecc0',
    storageBucket: 'vaidyagrama-eecc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-jXufL1XgnD1h_W_GxJQDWxf4ce7-dHo',
    appId: '1:355883310220:ios:0488705b614dffe2606fa9',
    messagingSenderId: '355883310220',
    projectId: 'vaidyagrama-eecc0',
    storageBucket: 'vaidyagrama-eecc0.firebasestorage.app',
    iosBundleId: 'in.easycloud.vaidyagrama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-jXufL1XgnD1h_W_GxJQDWxf4ce7-dHo',
    appId: '1:355883310220:ios:0488705b614dffe2606fa9',
    messagingSenderId: '355883310220',
    projectId: 'vaidyagrama-eecc0',
    storageBucket: 'vaidyagrama-eecc0.firebasestorage.app',
    iosBundleId: 'in.easycloud.vaidyagrama',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw-EL4ZDhV8ywPNanZWuK5OYM-3DZ-64M',
    appId: '1:355883310220:web:b3f2d7140f563d5c606fa9',
    messagingSenderId: '355883310220',
    projectId: 'vaidyagrama-eecc0',
    authDomain: 'vaidyagrama-eecc0.firebaseapp.com',
    storageBucket: 'vaidyagrama-eecc0.firebasestorage.app',
    measurementId: 'G-DMDD2ELDYJ',
  );
}
